alexdalitz/dnsruby

- lib/dnsruby/zone_reader.rb
- test/tc_zone_reader.rb
This fixes a bug where the zone reader would add @origin.to_s + "." to relative hostnames in the record data. Since @origin already ends with a dot, the result would be the hostname ending in two dots, which is invalid.
I also uncommented the test case I wrote for it in my last pull request.
> Fix zone reader adding unwanted dot to relative hostnames being converted to absolute

- lib/dnsruby/name.rb
- lib/dnsruby/resource/NAPTR.rb
- lib/dnsruby/resource/NSEC3.rb
- lib/dnsruby/resource/TXT.rb
I included dnsruby 1.57.0 in a project, and hit several Ruby warnings. I'd like to fix those up to reduce the noise in my tests (and make it easier to spot warnings that apply to my own code) - here's a pull request fixing the first few.
> Fix warnings

- lib/dnsruby/resolver.rb
Wrong argument is passed to the create_tsig_options in the Resolver.get_tsig function.
The function checks if args[0] is an Array and then it passes just args.
Fixing this makes AXFR w/ TSIG work again.
This is a sample working code.
```ruby
require 'dnsruby'
res = Dnsruby::Resolver.new
server = '127.0.0.1'
zone = 'example.com'
KEY_NAME = "dns-server.example.com"
KEY = "wI6XiocuMR8X/DySzKVbp2SdzZZeXCsQLjEs6HRlnkY=";
zt = Dnsruby::ZoneTransfer.new
zt.server = server
zt.transfer_type = Dnsruby::Types.AXFR
zt.tsig= KEY_NAME, KEY
zoneref = zt.transfer(zone)
```
> Fix args passed to create_tsig_opts

- lib/dnsruby/resolver.rb
- test/tc_resolver.rb
* Fix: options[:algorithm] was NOT an assignment
* Refactor arguments
* Add tests
> Refactor Resolver.create_tsig_options

- test/ts_offline.rb
- test/ts_online.rb
Did some cleanup on these test suite files, which call other test files (tc_*.rb).
Most importantly, I disabled the code that could never be run because the Nominet servers are no longer available.  I did that so that someone searching the code to see what tests could be run would not mistakenly believe that these files were being run under some circumstances.
Also:
* moved some code into methods, and then call them
* sorted test file lists alphabetically for easy lookup
* various cleanup and simplification
> Cleanup test suites

- lib/dnsruby.rb
We have some explicit requires (requires of specific files) in lib/dnsruby.rb.
While there may be some recursive requiring going on, not all the files are required as a result.  For example:
```
2.1.4 :001 > require 'dnsruby'
=> true
2.1.4 :002 > Dnsruby::Resolv
NameError: uninitialized constant Dnsruby::Resolv
```
This code modification requires all files in lib/dnsruby and below.  This is the simplest way to guarantee that all files are included.  The expansion of the wild card will also include the files already explicitly required, but require will notice this and not try to require the file again, so this is not a problem.
> Add code to require all Ruby files in and under lib/dnsruby.

- lib/dnsruby/resolv.rb
- test/tc_resolv.rb
This is a simple change but fixes a bad bug where trying to ask getaddress for the address of an IP address raises an error, but only on Linux, not on Mac OS.  I've added a test to verify the bug and the fix.  Here was the output of the failing test before the fix was applied:
1) Error:
TestResolv#test_resolv_address_to_address:
NoMethodError: undefined method `first' for "127.0.0.1":String
/home/kbennett/dnsruby/lib/dnsruby/resolv.rb:71:in `getaddress'
/home/kbennett/dnsruby/test/tc_resolv.rb:71:in `test_resolv_address_to_address'
> Fixed Resolv error when address passed was already an IP address.

- lib/dnsruby/packet_sender.rb
- lib/dnsruby/select_thread.rb
- test/tc_soak.rb
- test/tc_tcp_pipelining.rb
- test/test_dnsserver.rb
Also removed exception handling in NioTcpPipeliningHandler selector thread as per @nwitkowski.
Minor refactor of method that creates the selector thread.
> Removed "Note:" comments added in the previous commit.

- lib/dnsruby/message/message.rb
- test/tc_rr.rb
When adding an RR to a Dnsruby::Message, the original add_answer method checks to see if it already occurs, and, if so, does not add it again. 
This is a problem in the case of an AXFR response, where a SOA record needs to be added twice.  The add_answer! method added in this pull request allows the answer record to be answered whether or not it already occurs.
> Add Message#add_answer! method.

- demo/check_soa.rb
SOA result gets cached from the first nameserver queried, resulting in the below example (all are authoritative, and the ns1 server is running an old version).
$ ./demo/check_soa.rb example.net
ns2.company.dns.example.net (123.34.255.73): has serial number 2
ns1.company.dns.example.net (123.34.234.248): isn't authoritative for example.com
ns3.company.dns.example.net (50.17.205.23): isn't authoritative for example.com
$ ./demo/check_soa.rb example.com
ns3.company.dns.example.net (50.17.205.23): has serial number 2
ns2.company.dns.example.net (123.34.255.73): isn't authoritative for example.com
ns1.company.dns.example.net (123.34.234.248): isn't authoritative for example.com
$ ./demo/check_soa.rb example.com
ns1.company.dns.example.net (123.34.234.248): has serial number 1 …
> disable caching for SOA lookups

- lib/dnsruby/resource/TSIG.rb
Offline tests still pass.  Online tests still fail.  No change to tests, since only md5 algo is being tested.
```shell
$ rake test_offline
/home/junk/.rvm/rubies/ruby-2.0.0-p643/bin/ruby -I"lib" -I"/home/junk/.rvm/gems/ruby-2.0.0-p643@global/gems/rake-10.4.2/lib" "/home/junk/.rvm/gems/ruby-2.0.0-p643@global/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/ts_offline.rb"
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Run options: --seed 17350
.........................................................................................................................
Finished in 2.809492s, 43.0683 runs/s, 464.8528 assertions/s.
121 runs, 1306 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to …
```
> Add support for HMAC SHA512 TSIG keys

- .travis.yml
- lib/dnsruby.rb
Fixes the following deprecation error notice: 
```
/usr/local/lib/ruby/gems/2.3.0/gems/dnsruby-1.59.1/lib/dnsruby.rb:164: warning: constant Dnsruby::TimeoutError is deprecated
```
I don't know if this will have issues with older rubies. Hopefully travis catches them.
> ruby 2.3.0 deprecates TimeoutError, use Timeout::Error

- lib/dnsruby/bit_mapping.rb
- lib/dnsruby/code_mapper.rb
- lib/dnsruby/config.rb
- lib/dnsruby/packet_sender.rb
- lib/dnsruby/resolver.rb
- lib/dnsruby/resource/OPT.rb
- lib/dnsruby/resource/RRSIG.rb
Fix for https://github.com/alexdalitz/dnsruby/issues/115.
Changed Fixnum references to Integer for compatibility with Ruby >= 2.4.
> Remove fixnum and bignum

- test/run-tests-individually
- test/tc_resolver.rb
- Fix references to Message to Dnsruby::Message in TestRawQuery class.
- Add run-tests-individually script to see which, if any, tests run individually, will fail.
The tc_resolver.rb class was failing when run individually.  Previously I had removed the `include Dnsruby` but neglected to prefix `Message` with `Dnsruby::`. This did not produce an error when the tests were run in the usual way so it wasn't noticed until I ran the test individually.
> Fix test bug, add run-tests-individually script.

- test/tc_hs.rb
- test/ts_online.rb
As described in issue: https://github.com/alexdalitz/dnsruby/issues/112
> Fix issue #112 by removing a top level `include Dnsruby`

- lib/dnsruby/update.rb
- test/tc_update.rb
This patch allows for spaces in strings as well as arrays when deleting TXT records.  This makes it match what's allowed for adding a TXT record.
> Fix deletion of TXT records with spaces

- lib/dnsruby/resolver.rb
Tiny patch to pass `@port` through from Dnsruby::Resolver to the PacketSender(s).
> Fix use of non-default ports in Dnsruby::Resolver

- lib/dnsruby/select_thread.rb
It appears that a side-effect of requiring this library changes the global behavior of threads across the entire program. We noticed this while testing dnsruby in a Metasploit module. Is it sufficient just to remove this global change in behavior, or is this actually needed by dnsruby?
> avoid changing global thread abort behavior

- README.md
Supported since v0.60.1: https://github.com/alexdalitz/dnsruby/blob/master/RELEASE_NOTES.md#v1601
/cc @alexdalitz
> README: add CAA to list of records supported by this library

- lib/dnsruby/resource/DNSKEY.rb
It would be helpful for readers of the code to explain why this needed to be done, so I added comments explaining.
> Add explanation of need for begin/rescue block for setting openssl keys.

- Gemfile
- dnsruby.gemspec
- lib/dnsruby/name.rb
- test/tc_name.rb
```
["hoge/hoge","hoge#hoge","hoge?hoge"].each do |d|
pp "input #{d}"
pp "output #{Dnsruby::Name.create(d)}"
end
"input hoge/hoge"
"output hoge"
"input hoge#hoge"
"output hoge"
"input hoge?hoge"
"output hoge"
```
> Fix create name include url special characters

- lib/dnsruby/resource/DNSKEY.rb
- lib/dnsruby/single_verifier.rb
- lib/dnsruby/validator_thread.rb
- test/tc_dnskey.rb
- test/tc_verifier.rb
Makes it possible to validate DNSSEC data for algorithms 13 and 14. Has been tested with ECDSAP256SHA256, but alg 14 should follow the same logic.
> Implement ECDSAP256SHA256 (13) / ECDSAP384SHA384 (14) algorithms

- lib/dnsruby/dnssec.rb
Simple fix to Dnsruby::Dnssec.reset method. Caused some dnssec-enabled domains to report invalid security level after using this method because one of the keys was not reinitialized.
> Reinitialize all IANA TAR keys with Dnssec.reset

- test/tc_resolver.rb
Prior to this commit we were seeing a deprecation warning when running
tests locally on Ruby 2.7.1 (e.g. https://travis-ci.org/github/alexdalitz/dnsruby/jobs/715103346).
```
test/tc_resolver.rb:174: warning: deprecated Object#=~ is called on FalseClass; it always returns nil
```
`!RUBY_PLATFORM=~/darwin/` was always returning `nil` because
`!RUBY_PLATFORM` returned `false`, then we called `false =~ /darwin/`.
Co-authored-by: Adam Hess <hparker@github.com>
> Fix Ruby 2.7 deprecation warning in tests

- .travis.yml
- lib/dnsruby/config.rb
- lib/dnsruby/hosts.rb
Prior to this commit we were seeing errors when calling the deprecated
Object#untaint method on Ruby 2.8. The method is a no-op on Ruby 2.8.
```rb
dnsruby/config.rb:325: warning: Object#untaint is deprecated and will be removed in Ruby 3.2
```
We probably could remove untainting for older Ruby versions as well, but
it felt safer to preserve the current behavior in case someone is still
relying on it.
To see this change in action, we added ruby-head to the travis matrix,
but do not require those tests to pass for the build as a whole to pass.
See https://bugs.ruby-lang.org/issues/16131 for details on the
deprecation.
> Address Ruby 2.8 #untaint deprecation warnings

- lib/dnsruby/DNS.rb
- lib/dnsruby/config.rb
- lib/dnsruby/message/encoder.rb
- lib/dnsruby/message/header.rb
- lib/dnsruby/name.rb
- lib/dnsruby/packet_sender.rb
- lib/dnsruby/recursor.rb
- lib/dnsruby/resolver.rb
- lib/dnsruby/resource/CAA.rb
- lib/dnsruby/resource/NSEC3PARAM.rb
- lib/dnsruby/resource/TLSA.rb
- lib/dnsruby/select_thread.rb
- lib/dnsruby/single_verifier.rb
- lib/dnsruby/zone_reader.rb
- lib/dnsruby/zone_transfer.rb
- test/spec_helper.rb
- test/tc_resolver.rb
- test/tc_tcp.rb
- test/test_utils.rb
DNSRuby generates tons of unused variable and other ruby warnings.
That's a problem for applications and libraries depending on it and trying to catch issues on CI/test with these warnings.
This PR clear most warnings, there's still a bunch in the test suite, but I believe it's a good start.
> Clear Ruby warnings

- lib/dnsruby/recursor.rb
While tracking down an issue with failed recursive lookups, wireshark analysis determined that the requests were being sent with the 'rd' flag even though the docs for Dnsruby::Recursor shows that should not be the case.
This patch ensures the rd flag is not set on these requests.
> Ensure Recursor sends requrests without the rd flag set

- dnsruby.gemspec
- lib/dnsruby/dnssec.rb
So turns out `Net::FTP` isn't used by dnsruby since a good decade, the `require` was just left there. Sorry I should have checked before adding the dependency.
It was introduced in 58c05cd2596d1daad11b565d22cf187a9babddce (2009) to download IANA tar archive, but removed in f9b99a11ff83ebdbe44dae273931184415f90b5a (2010).
But no big deal.
> Remove dependency on net-ftp

- lib/dnsruby/resource/DS.rb
There are a few requires to "digest" in this library, but this is the only one attempting the require using title case.
Some users on case-insensitive filesystems were reported strange results because of this (which I didn't totally figure out). I think it's best to just require the right library name from the right place.
> Remove require to titlecased Digest

- lib/dnsruby/resource/CAA.rb
- test/tc_caa.rb
When a CAA record is incorrectly formatted dnsruby throws a `NoMethod` error.
```
kdig +bufsize=1280 @8.8.8.8 -t CAA buda.com
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 44583
;; Flags: qr rd ra ad; QUERY: 1; ANSWER: 15; AUTHORITY: 0; ADDITIONAL: 1
;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR
;; QUESTION SECTION:
;; buda.com.                IN  CAA
;; ANSWER SECTION:
buda.com.               451 IN  CAA 0 comodoca.com "issue"
buda.com.               451 IN  CAA 0 comodoca.com "issuewild"
buda.com.               451 IN  CAA 0 digicert.com "issue"
buda.com.               451 IN  CAA 0 digicert.com "issuewild"
buda.com.               451 IN  CAA 0 issue "comodoca.com"
buda.com.               451 IN  CAA 0 issue "digicert.com; …
```
> Raises ArgumentError when trying to parse an invalid CAA record

- lib/dnsruby/resource/CAA.rb
This helps with debugging to see the record that DnsRuby sees. It also helps if the DNS record changed between when the exception was raised and when you view the logs. This happens a lot with our infrastructure 🙂 LMK if this is sane/useful!
> Include the DNS record received when unable to parse a CAA record

- lib/dnsruby/resource/CAA.rb
This will parse case insensitive property tags for CAA records per the RFCs.
https://github.com/alexdalitz/dnsruby/issues/201
> allow parsing case insensitive property tags for CAA records

- RELEASE_NOTES.md
- dnsruby.gemspec
> add logger as dependency for ruby 3.5 support

- .github/workflows/ci.yml
- dnsruby.gemspec
- lib/dnsruby/resource/DNSKEY.rb
- test/spec_helper.rb
* Allow newer base64, logger
* Use newer minitest for Ruby 3.4 compat
* Update CI for Ruby 3.4
* Fix Ruby warning
> Gem and Ruby 3.4 updates

- lib/dnsruby/resolver.rb
- test/tc_resolver.rb
- test/tc_single_resolver.rb
This PR adds automatic support for EDNS (Extension Mechanisms for DNS) in Dnsruby when the udp_size configuration is set >512 bytes, even if dnssec is false. Previously, queries with larger UDP sizes wouldn't include the required OPT resource record, causing truncation and TCP fallbacks for responses exceeding 512 bytes (e.g., large TXT or SPF records). This change checks for udp_size > 512 during message preparation and adds a basic EDNS0 OPT RR if none exists, following RFC 6891 for improved compatibility with modern DNS servers.
> Automatically add EDNS OPT RR when udp_size >512, even if dnssec=false
